### ISSUE TITLE
Failed to load a language-chialisp package grammar

### ISSUE THREAD

**Issue by BrandtH22** [Quexington/language-chialisp#1]
I am at a loss at how to resolve the below error: 
I have tried installing the chialisp language package in both the manual and automated fashions on different devices and operating systems but have received an error each time. Is the below referenced module "tree-sitter-chialisp" contained within the .zip or is this compiled at time of installation? Is it possible to manually load this module?

1. download .zip from Github
2. extract and copy contents to ~/.atom/packages directory
3. ran apm i from project directory
4. open project in Atom
5. error appears upon opening Atom:

"Cannot find module 'tree-sitter-chialisp'
Require stack:
- C:\Users\donot\.atom\packages\language-chialisp-master\grammars\chialisp.cson in C:\Users\donot\.atom\packages\language-chialisp-master\grammars\chialisp.cson"

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-chialisp](https://github.com/Quexington/language-chialisp) package 1.0.4

### Stack Trace

Failed to load a language-chialisp package grammar

```
At Cannot find module 'tree-sitter-chialisp'
Require stack:
- C:\Users\donot\.atom\packages\language-chialisp-master\grammars\chialisp.cson in C:\Users\donot\.atom\packages\language-chialisp-master\grammars\chialisp.cson

Error: Cannot find module 'tree-sitter-chialisp'
Require stack:
- C:\Users\donot\.atom\packages\language-chialisp-master\grammars\chialisp.cson
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (<embedded>:11:157920)
    at new TreeSitterGrammar (<embedded>:11:3432197)
    at GrammarRegistry.createGrammar (<embedded>:11:362991)
    at <embedded>:11:362832
    at u (<embedded>:11:584283)
    at <embedded>:11:585520
    at FSReqCallback.oncomplete (fs.js:158:21)

  at /packages/language-chialisp-master/grammars/chialisp.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
language-chialisp 1.0.4 
```

**Comment by BrandtH22** [comment]
Closed to non-response
